# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on: pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo ${{ github.event.pull_request.body }}
